name: Code Quality and Docs Check

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # FIX 1: Replaced the old "Install and configure" step with a simple, correct install.
      - name: Install uv
        run: pip install uv
        
      # FIX 2: Renamed step for clarity. This step prepares the cache directory.
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ./.uv-cache
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      # FIX 3: Added the 'env' block to tell uv where the cache is. This is the crucial fix.
      - name: Install dependencies with uv
        env:
          UV_CACHE_DIR: ./.uv-cache
        run: |
          uv pip install --system ruff sphinx sphinx-rtd-theme sphinx-autoapi

      - name: Get changed Python files
        id: changed-py-files
        uses: tj-actions/changed-files@v44 # A dedicated action for this
        with:
          files: |
            **/*.py

      - name: Run Ruff Linter
        if: steps.changed-py-files.outputs.any_changed == 'true'
        run: |
          echo "Linting changed files..."
          ruff check ${{ steps.changed-py-files.outputs.all_changed_files }}

      - name: Test build documentation
        run: |
          # Use the repository's name for the project name
          REPO_NAME=${{ github.event.repository.name }}
          
          if [ ! -d docs ]; then
            echo "Initializing docs for build test..."
            sphinx-quickstart docs -q -p "$REPO_NAME" -a "GitHub Actions" --ext-autodoc
            cat << EOF >> docs/source/conf.py
          extensions.append('autoapi.extension')
          autoapi_type = 'python'
          autoapi_dirs = ['../']
          html_theme = 'sphinx_rtd_theme'
          EOF
          fi
          
          # Attempt to build the docs to catch any errors
          make -C docs html
