name: Build and Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      # Added pyproject.toml to the trigger paths
      - '**.py'
      - 'docs/**'
      - 'pyproject.toml'
      - '.github/workflows/deploy-docs.yaml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # FIX 1: Replaced the failing "Install and configure" step.
    - name: Install uv
      run: pip install uv

    # FIX 2: Renamed for clarity and ensured the key is correct.
    - name: Restore uv cache
      uses: actions/cache@v4
      with:
        path: ./.uv-cache
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    # FIX 3: Added the 'env' block and now using pyproject.toml for dependencies.
    - name: Install dependencies with uv
      env:
        UV_CACHE_DIR: ./.uv-cache
      run: |
        uv pip install --system .[dev,docs]

    # FIX 4: Added the '--sep' flag for sphinx robustness, as we did in the CI workflow.
    - name: Build documentation
      run: |
        REPO_NAME=${{ github.event.repository.name }}
        
        if [ ! -d docs ]; then
          sphinx-quickstart docs -q -p "$REPO_NAME" -a "GitHub Actions" --sep --ext-autodoc
          cat << EOF >> docs/source/conf.py
        extensions.append('autoapi.extension')
        autoapi_type = 'python'
        autoapi_dirs = ['../']
        html_theme = 'sphinx_rtd_theme'
        EOF
        fi
        
        make -C docs clean
        make -C docs html

    - name: Deploy to external docs repository
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.DOCPUSHING }}
        external_repository: AaravAgarwal/doc_test_3
        publish_dir: ./docs/build/html
        publish_branch: main
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Docs update for ${{ github.sha }}'
        destination_dir: ${{ github.event.repository.name }}
        keep_files: false
