name: Update Documentation Landing Page
on:
  push:
    branches:
      - main  
jobs:
  updateLandingPage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Index Page
        run: |
          echo "Generating dynamic index.html"

          # Start the HTML content
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Documentation</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
                  h1 { color: #333; }
                  ul { list-style-type: none; padding: 0; }
                  li { margin: 10px 0; }
                  a { text-decoration: none; color: #0066cc; }
                  a:hover { text-decoration: underline; }
              </style>
          </head>
          <body>
              <h1>Documentation Portal</h1>
              <p>Welcome! Click on a project below to view its documentation:</p>
              <ul>
          EOF

          # Loop through documentation folders and generate links
          for folder in */ ; do
              [[ -d "$folder" && "$folder" != .* ]] || continue  # Exclude hidden folders
              project_name=$(basename "$folder")
              echo "Adding $project_name to index.html"
              echo "<li><a href='./${project_name}/index.html'>${project_name} Documentation</a></li>" >> index.html
          done

          # Close the HTML content
          cat <<EOF >> index.html
              </ul>
          </body>
          </html>
          EOF

          # Ensure the index.html is not empty before committing
          if [[ ! -s index.html ]]; then
              echo "No documentation folders found. Skipping commit."
              exit 0
          fi

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "aarav3@illinois.edu"
          git config --global user.name "AaravAgarwal"

          git add index.html
          git diff --cached --quiet || (git commit -m "Update dynamic index.html" && git push origin main)
