name: Build and Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - 'docs/**'
      - '.github/workflows/deploy-docs.yaml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install and configure uv
      run: |
        pip install uv
        uv config set cache-dir ./.uv-cache

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ./.uv-cache
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}

    - name: Install dependencies with uv
      run: |
        uv pip install --system sphinx sphinx-rtd-theme sphinx-autoapi

    - name: Build documentation
      run: |
        REPO_NAME=${{ github.event.repository.name }}
        
        if [ ! -d docs ]; then
          sphinx-quickstart docs -q -p "$REPO_NAME" -a "GitHub Actions" --ext-autodoc
          cat << EOF >> docs/source/conf.py
        extensions.append('autoapi.extension')
        autoapi_type = 'python'
        autoapi_dirs = ['../']
        html_theme = 'sphinx_rtd_theme'
        EOF
        fi
        
        make -C docs clean
        make -C docs html

    - name: Deploy to external docs repository
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.DOCPUSHING }}
        external_repository: AaravAgarwal/doc_test_3
        publish_dir: ./docs/build/html
        publish_branch: main
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Docs update for ${{ github.sha }}'
        # The repo-named folder in the target repository
        destination_dir: ${{ github.event.repository.name }}
        keep_files: false
